config/routes.rb
Rails.application.routes.draw do
  
  
  resources :charges, only: [:new] do 
    collection do 
      post :charge 
      post :downgrade
    end
  end
  resources :wikis do
    member do
      post :add_collaborator 
      delete '/remove_collaborator/:user_id', to: 'wikis#remove_collaborator', as: :remove_collaborator
    end
  end
  devise_for :users
  get 'welcome/index'

  get 'welcome/about'

  root "welcome#index"

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
	belongs_to :user
	belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis
  has_many :collaborations
  has_many :collaborating_wikis, through: :collaborations, source: :wiki
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  enum role: [:standard, :admin, :premium]
  after_initialize :default_role
  
  def default_role
  	self.role ||= :standard
  end
  
  def upgrade
  	self.role = :premium
  	self.save
  end

  def downgrade
  	self.role = :standard
  	self.save

    wikis.each do |wiki|
      wiki.private = false
      wiki.save
    end

  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :creator, class_name: "User", foreign_key: :user_id
  #pretend its a user but call it creator
  has_many :collaborations
  has_many :collaborators, through: :collaborations, source: :user
  
  before_create { self.private = self.private || false; true}

  scope :public_view, -> {where(private: false)}

  scope :private_view, -> {where(private: true)} 

 
 def self.visible_to (user)
	
 		if user.admin?
 				all
 		elsif user.premium? 
 				where("(private = ?) OR ((private = ?) AND (user_id = ?))", false, true, user.id)
 		elsif user.standard?
 				where(private: false)
 		end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  
  #before_action :configure_permitted_parameters, if: :devise_controller?

  #protected

  #def configure_permitted_parameters
   # devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  #end
#end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  @amount = 15_00
   def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "BigMoney Membership - #{current_user.email}",
     amount: @amount
   }
  end

  def charge
   @amount = 15_00
   # Creates a Stripe Customer object, for associating
   # with the charge
   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )
   
   # Where the real magic happens
   charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: @amount,
     description: "BigMoney Membership - #{current_user.email}",
     currency: 'usd'
   )
 
   flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
   current_user.upgrade
   redirect_to root_path # or wherever
 
   # Stripe will send back CardErrors, with friendly messages
   # when something goes wrong.
   # This `rescue block` catches and displays those errors.
   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
  end

  def downgrade
    current_user.downgrade
    flash[:notice] = "Your account has been downgraded back to a Standard Account."
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :about]	

  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  #before_action :setter_wiki, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :show


  def index
    @wikis = Wiki.visible_to(current_user)
    @collabwiki = current_user.collaborating_wikis

  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @collabwiki = current_user.collaborating_wikis
    @user = User.find_by(params[:user_id]) #_by(email: params[:collaborator][:email]))

  end

  def create
     @wiki = Wiki.new(wiki_params)
     @wiki.creator = current_user



     if @wiki.save
       flash[:notice] = "Post was saved successfully."
       redirect_to @wiki
     else
 
       flash.now[:alert] = "There was an error saving the post. Please try again."
       render :new
     end
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Post was updated"
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the post please try again"
      render :edit
    end
  end

  def destroy
      @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully"
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the post"
      render :show
    end
  end
  
  def add_collaborator
    #@collaborator = Collaborator.new(params[:id])
    #@wiki = Wiki.find(params[:id])
    #if @wiki.save
    #  @wiki.collaborators = Collaborator.update_collaborators(params[:user][:collaborators])
    #  flash[:alert] = "Collaborator saved"
    #else  
    #  flash[:alert] = "Collaborator not saved, error -  please try again"
    #end
    @wiki = Wiki.find(params[:id])
    @user = User.find_by(email: params[:collaborator][:email])
      if @wiki.collaborators.include?(@user)
        flash[:alert] = "That user is already a collaborator."
      elsif @user.nil?
        flash[:alert] = "this user does not exist"
      else
        @wiki.collaborators << @user
      end
    redirect_to edit_wiki_path(@wiki)
  end  

  def remove_collaborator
   @wiki = Wiki.find(params[:id])
   collaboration = Collaboration.find_by(wiki_id: params[:id], user_id: params[:user_id])


     if collaboration.destroy
      flash[:notice] = "Collab Deleted"
      redirect_to edit_wiki_path(@wiki)
     else
      flash[:alert] = "Collab could not be deleted."
      redirect_to edit_wiki_path(@wiki)
     end
     
  end  

  private
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, :user_id)
  end



  def authorize_user
      unless current_user.admin? || current_user.premium?
          flash[:alert] = "You must have upgraded privlidges to do that. please upgrade your account."
          redirect_to wikis_path
      end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
		options = { filter_html: true, hard_wrap: true, space_after_headers: true, fenced_code_blocks: true }   
	    extensions = { autolink: true, superscript: true, disable_indented_code_blocks: true }    
	    renderer = Redcarpet::Render::HTML.new(options)	   
	    markdown = Redcarpet::Markdown.new(renderer, extensions)
	    markdown.render(text).html_safe
	end
end

app/helpers/charges_controller_helper.rb
module ChargesControllerHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/charge.html.erb
<h1>Welcome#charge</h1>

app/views/charges/new.html.erb
 <%= form_tag charge_charges_path do %>
   <h4>Click the button!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

app/views/collaborators/destroy.html.erb
<h1>Collaborators#destroy</h1>
<p>Find me in app/views/collaborators/destroy.html.erb</p>

app/views/collaborators/edit.html.erb
<h1>Collaborators#edit</h1>
<p>Find me in app/views/collaborators/edit.html.erb</p>

app/views/collaborators/index.html.erb
<h1>Manage Collaborators</h1>
<h3>Wiki: <em><%= @wiki %></em></h3>
<h3>Owner: <em><%= @wiki.user.email %></em></h3>

<table class="table table-striped">
  <thead>
    <th>User</th>
    <th></th>
  </thead>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td>
        <!-- check if user is a collaborator -->
        <% if @wiki.collaborators.include?(user) %>
        <!-- if so, show remove button -->
          <% collaborator = @wiki.collaborator(user) %>
          <%= link_to "Remove as collaborator", [@wiki, collaborator], method: :delete, class: "btn btn-danger" %>
        <% else %>
        <!-- else show add button -->
          <%= link_to "Add as collaborator", wiki_collaborators_path(@wiki, user_id: @user.id), method: :post, class: "btn btn-success" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/collaborators/new.html.erb
<h1>Collaborators#new</h1>
<p>Find me in app/views/collaborators/new.html.erb</p>

app/views/collaborators/show.html.erb
<h1>Collaborators#show</h1>
<p>Find me in app/views/collaborators/show.html.erb</p>

app/views/collaborators/update.html.erb
<h1>Collaborators#update</h1>
<p>Find me in app/views/collaborators/update.html.erb</p>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
 <html>
 <head>
   <title>Bloccit</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <%= stylesheet_link_tag    "application", media: "all" %>
   <%= javascript_include_tag "application" %>
   <%= csrf_meta_tags %>
 </head>
 <body>
  
   <div class="container">
     <ul class="nav nav-tabs">
       <li><%= link_to "Jigipedia", welcome_index_path %></li>
       <li><%= link_to "Wikis", wikis_path %></li>
       <li><%= link_to "About", welcome_about_path %></li>
       <% if user_signed_in? && current_user.standard? %>
       <li><%= link_to "Upgrade Account", charge_charges_path, method: :post %></li>
       <% elsif user_signed_in? && current_user.premium?  %>
       <li><%= link_to "Downgrade Account", downgrade_charges_path, method: :post %></li>
       <% end %>

         <div class="pull-right">
           <% if user_signed_in? %>
              Signed in as: <strong><%= current_user.email %></strong> |
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

          <% else %>
              <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
              <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
          <% end %> 
        </div>

     </ul> 
   </div>

  <div class ="flash">
    <% if flash[:notice] %>
      <div class = "alert alert-success">
        <button type="button" class="close" data-dismiss = "alert"> &times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div class = "alert alert-danger">
        <button type="button" class="close" data-dismiss = "alert"> &times;</button>
        <%= flash[:alert] %>
      </div>
      <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
      <% end %>
    </div>
    <%= yield %>
  </div>

 </body>
 </html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="container">
<div class="starter-template">
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="page-header">
				<h1>
					Jigipedia
				</h1>
			</div>
			<div class="jumbotron well">
				<h2>
					A Personalized Wikipedia Collaberation tool
				</h2>
				<p>
					Developed by Jigesh Parekh
				</p>
			</div>
			<blockquote>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.
				</p> <small>Someone famous <cite>Source Title</cite></small>
			</blockquote>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4">
			<h2>
				Free Plan
			</h2>
			<p>
				Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
			</p>
			<p>
				<a class="btn" href="#">View details »</a>
			</p>
		</div>
		
		<div class="col-md-4">
		</div>

		<div class="col-md-4">
			<h2>
				Premium Plan
			</h2>
			<p>
				Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
			</p>
			<p>
				<a class="btn" href="#">View details »</a>
			</p>
		</div>
	</div>
</div>

</div>
</div>

app/views/wikis/_collab.html.erb
<h4>Add a collaborator</h4>
<% @users.each do |user| %>
	<%= form_for(@wiki) do |f| %>
		 <% if @wiki.creator == current_user || current_user.admin? %>
			 <div class="form-group">
			  <%= f.email_field :collaborator_email %>
			 </div

			 <%= f.submit "Submit Collaborator", class: 'btn btn-default pull-right' %>
 		<% end %> 
	<% end %>
<% end %>  

app/views/wikis/create.html.erb
<h1>Wikis#create</h1>
<p>Find me in app/views/wikis/create.html.erb</p>

app/views/wikis/destroy.html.erb
<h1>Wikis#destroy</h1>
<p>Find me in app/views/wikis/destroy.html.erb</p>

app/views/wikis/edit.html.erb
  <%= form_for @wiki do |f| %>
    <div class="container">
      <div class="starter-template">
        <h1>
          Edit Wiki
        </h1>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title , class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, class:"form-control" %>
        </div>
      </div>
     <%= f.submit "Update", class:"btn btn-success pull-right" %>

     <%= link_to "Cancel and Return to Wiki", wikis_path, :class => 'btn btn-link pull-left'  %>
  </div> 
 <% end %>

<% if current_user.premium? || current_user.admin? %> 
    <% if @wiki.private %> 
        <%= form_for :collaborator, url: add_collaborator_wiki_path(@wiki) do |f| %>   
          <div class= "container">
            <h2> Add Collaborator </h2>
            <div class= "form-group"> 
              <%= f.email_field :email %>
              <%= f.submit %> 
            </div>
          </div>
        <% end %> 
          
        <div class= "container">
          <h2> Collaborators List </h2>
            <div class= "form-group"> 
              <% @wiki.collaborators.each do |user| %> 
                <%= user.email %> 
                <%= link_to "Remove from Collab", remove_collaborator_wiki_path(@wiki, user), method: :delete, :class =>"btn btn-danger" %>
                </br>
              <% end %> 
            </div>
        </div>
   <% end %>
<% end %>

app/views/wikis/index.html.erb
<div class="container">
<div class="starter-template">


 <h1>Wikis</h1>

 <div class="row">
   <div class="col-md-8">
 
     <% @wikis.each do |wiki| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
 
             <%= link_to wiki.title, wiki %>
           </h4>
          
         </div>
       </div>
     <% end %>



 
     <% @collabwiki.each do |wiki| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">

             <%= link_to wiki.title, wiki %>
           </h4>
          
         </div>
       </div>
     <% end %>
   </div>
  
   <div class="col-md-4">
     <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
   </div>
 </div>


</div>
</div>

app/views/wikis/new.html.erb
 <%= form_for @wiki do |f| %>
    <div class="container">
      <div class="starter-template">
        <h1>
          New Wiki
        </h1>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title , class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, class:"form-control" %>
        </div>
      </div>
        
  
    <!-- /.container -->
 

    <% if current_user.admin? || current_user.premium? %>
      <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
          <%= f.check_box :private %> Private wiki
        <% end %>
      </div>

    <% end %>
  <%= f.submit "Save", class:"btn btn-success pull-right" %>
  </div>
<% end %>

app/views/wikis/show.html.erb
<div class="container">
<div class="starter-template">
	<div>
			<h1>
				<%= @wiki.title %> <br>
				<h3 style="margin-top: -10px">
				<small>
					submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.creator %>
				</small>
			</h3>
			</h1>
			<br>
			<br>
			<p>
				<%= markdown(@wiki.body) %> <br>
			</p>
	</div>

	<div class="row">
		    <div class="col-md-8">
		    </div>
		  
			<div class = "col-md-4">
			<%= link_to "Edit", edit_wiki_path(@wiki.id, @wiki), class: 'btn btn-success' %>

		     <%= link_to "Delete wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
			</div>
	</div>
</div>
</div>

app/views/wikis/update.html.erb
<h1>Wikis#update</h1>
<p>Find me in app/views/wikis/update.html.erb</p>